version: '3.9'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: laravel8_nginx
    volumes:
      - ./src:/var/www
      - ./nginx/conf:/etc/nginx/conf.d 
    ports:
      - "8123:80"
    restart: always
    networks:
      - web_network
    depends_on:
      - app
      - mysql
  mysql:
    image: mysql:8.0
    container_name: laravel8_mysql
    volumes:
      - ./database/data:/var/lib/mysql
    env_file:
      - ./env/mysql.env
    ports:
      - "3307:3306"
    restart: always
    networks:
      - web_network
  app:
    build:
      context: .
      dockerfile: ./dockerfiles/php.dockerfile
    image: laravel8-app
    container_name: laravel8_app
    volumes:
      - ./src:/var/www
    restart: always
    networks:
      - web_network
  redis:
    image: redis:6.2.1-buster
    container_name: laravel8_redis
    volumes:
      - ./redis/data:/data
    restart: always
    tty: true
    networks:
      - web_network
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: laravel8_mailhog
    ports:
      - "8025:8025"
    restart: always
    tty: true
    networks:
      - web_network
  phpmyadmin:
    image: phpmyadmin:5.1.0-apache
    depends_on:
      - mysql
    container_name: laravel8_phpmyadmin
    env_file:
      - ./env/phpmyadmin.env
    ports:
      - 8200:80
    restart: always
    networks:
      - web_network
networks:
  web_network:
    name: laravel8
    driver: bridge

